<?php

namespace App\Console\Commands;

use App\Http\Controllers\Admin\SpecialGroupController;
use App\Models\Agent;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;

// -------------------------------------------------------
// NEW 16 Jul 2026 — one-time bulk seed of Introducers under each of the
// 14 PVATM regional Team Leaders (created earlier by pvatm:import-tls).
// Chris did not supply a real name list for this batch, so full names
// are script-generated by randomly combining common Malay, Chinese, and
// Indian Malaysian name parts (not real individuals) — per his request
// to avoid generic "Introducer 01" placeholders and reflect a realistic
// ethnic mix.
//
// Each Introducer's address is copied exactly from their own TL's
// office address/postcode/city/state (per Chris's instruction that the
// address must follow the TL's state) — not fabricated separately.
//
// Agent codes are generated the normal way via HierarchyService
// (through createAgentForImport() -> createAgent()), so they come out
// as 3-1-1, 3-1-2, ... 3-1-19 etc. under each TL (e.g. 3-1), matching
// the numbering scheme in the master spec.
//
// Count per TL is a random 15-25, but everything (count, ethnicity mix,
// exact names, phone numbers) is seeded deterministically from the TL's
// own agent_code, so --dry-run always previews exactly what the real
// run will create.
//
// Run once via: php artisan pvatm:seed-introducers
// Add --dry-run to preview without writing anything.
// -------------------------------------------------------
class SeedPvatmIntroducers extends Command
{
    protected $signature = 'pvatm:seed-introducers {--dry-run : Preview without inserting anything}';
    protected $description = 'Bulk-seed 15-25 Introducers (randomly-generated Malay/Chinese/Indian names) under each PVATM regional Team Leader';

    private const GL_EMAIL = 'cateow@generallink.my';
    private const MIN_PER_TL = 15;
    private const MAX_PER_TL = 25;

    // Roughly reflects Malaysia's ethnic mix: ~55% Malay, 30% Chinese, 15% Indian.
    private const MALAY_MALE_FIRST = ['Ahmad', 'Mohd Faizal', 'Amir', 'Azman', 'Zulkifli', 'Rosli', 'Hafiz', 'Fadzil', 'Shahrul', 'Iskandar', 'Hakim', 'Nizam', 'Rashid', 'Anwar', 'Yusof'];
    private const MALAY_FEMALE_FIRST = ['Siti Aminah', 'Noraini', 'Fatimah', 'Zainab', 'Halimah', 'Rosnah', 'Norliza', 'Aishah', 'Suriani', 'Salmah'];
    private const MALAY_SURNAME = ['Ismail', 'Abdullah', 'Rahman', 'Hassan', 'Salleh', 'Yaakob', 'Othman', 'Idris', 'Zainal', 'Mahmud', 'Karim', 'Bakar'];

    private const CHINESE_SURNAME = ['Tan', 'Lim', 'Lee', 'Wong', 'Chong', 'Ng', 'Ong', 'Goh', 'Chan', 'Yap', 'Teh', 'Low', 'Koh', 'Yeoh'];
    private const CHINESE_GIVEN = ['Wei Ming', 'Siew Hoon', 'Kok Wei', 'Mei Ling', 'Chee Keong', 'Li Ping', 'Boon Huat', 'Yee Ching', 'Chun Hong', 'Poh Lin', 'Wei Jian', 'Xin Yi'];

    private const INDIAN_MALE_FIRST = ['Suresh', 'Ramesh', 'Muthu', 'Anand', 'Raju', 'Kannan', 'Vijay', 'Sathish', 'Kumaran', 'Manickam'];
    private const INDIAN_FEMALE_FIRST = ['Kavitha', 'Priya', 'Vasantha', 'Devi', 'Shanti', 'Latha', 'Rani', 'Meena', 'Geetha', 'Malar'];
    private const INDIAN_FATHER = ['Ramasamy', 'Muniandy', 'Subramaniam', 'Krishnan', 'Govindasamy', 'Perumal', 'Nathan', 'Rajoo', 'Veerasamy', 'Chandran'];

    /** Returns a random full name (Malay/Chinese/Indian mix, weighted 55/30/15). */
    private function randomName(): string
    {
        $roll = mt_rand(1, 100);
        $male = mt_rand(0, 1) === 1;

        if ($roll <= 55) {
            // Malay
            $first = $male ? self::MALAY_MALE_FIRST[array_rand(self::MALAY_MALE_FIRST)] : self::MALAY_FEMALE_FIRST[array_rand(self::MALAY_FEMALE_FIRST)];
            $surname = self::MALAY_SURNAME[array_rand(self::MALAY_SURNAME)];
            return $first . ($male ? ' bin ' : ' binti ') . $surname;
        }

        if ($roll <= 85) {
            // Chinese
            $surname = self::CHINESE_SURNAME[array_rand(self::CHINESE_SURNAME)];
            $given = self::CHINESE_GIVEN[array_rand(self::CHINESE_GIVEN)];
            return $surname . ' ' . $given;
        }

        // Indian
        $first = $male ? self::INDIAN_MALE_FIRST[array_rand(self::INDIAN_MALE_FIRST)] : self::INDIAN_FEMALE_FIRST[array_rand(self::INDIAN_FEMALE_FIRST)];
        $father = self::INDIAN_FATHER[array_rand(self::INDIAN_FATHER)];
        return $first . ($male ? ' a/l ' : ' a/p ') . $father;
    }

    /** Turns a generated full name into a safe, lowercase email local-part. */
    private function slugify(string $name): string
    {
        $name = str_ireplace([' bin ', ' binti ', ' a/l ', ' a/p '], ' ', $name);
        $name = strtolower(trim($name));
        $name = preg_replace('/[^a-z0-9\s]/', '', $name);
        $name = preg_replace('/\s+/', '.', trim($name));
        return $name;
    }

    public function handle(): int
    {
        $gl = Agent::where('email', self::GL_EMAIL)->where('is_deleted', false)->first();
        if (!$gl) {
            $this->error('Could not find GL account: ' . self::GL_EMAIL);
            return self::FAILURE;
        }
        if ($gl->role !== 'GROUP_LEADER' || !$gl->group_label_id) {
            $this->error('cateow@generallink.my is not a Group Leader of an Organization Rewards Group.');
            return self::FAILURE;
        }

        $teamLeaders = Agent::where('parent_id', $gl->agent_id)
            ->where('role', 'TEAM_LEADER')
            ->where('group_label_id', $gl->group_label_id)
            ->where('is_deleted', false)
            ->orderBy('agent_code')
            ->get();

        if ($teamLeaders->isEmpty()) {
            $this->error('No Team Leaders found under ' . $gl->full_name . '. Run pvatm:import-tls first.');
            return self::FAILURE;
        }

        $dryRun = (bool) $this->option('dry-run');
        $this->info(($dryRun ? '[DRY RUN] ' : '') . 'Seeding Introducers under ' . $teamLeaders->count() . ' Team Leader(s)...');

        $controller = app(SpecialGroupController::class);
        $totalCreated = 0;
        $totalSkipped = 0;

        foreach ($teamLeaders as $tl) {
            $profile = DB::table('agent_profiles')->where('agent_id', $tl->agent_id)->first();
            if (!$profile) {
                $this->warn("SKIP TL {$tl->agent_code} ({$tl->full_name}): no office address on file.");
                continue;
            }

            // Deterministic per-TL seed so dry-run and the real run
            // always agree on count, names, and phone numbers.
            mt_srand(crc32($tl->agent_code));
            $count = mt_rand(self::MIN_PER_TL, self::MAX_PER_TL);

            $this->line("TL {$tl->agent_code} ({$tl->full_name}) — {$profile->city}, {$profile->state}: seeding {$count} Introducer(s)");

            $created = 0;
            $skipped = 0;
            $codeSlug = str_replace('-', '', $tl->agent_code);
            $usedSlugs = [];

            for ($i = 1; $i <= $count; $i++) {
                $seq = sprintf('%02d', $i);
                $fullName = $this->randomName();
                $baseSlug = $this->slugify($fullName);

                // Guard against two randomly-generated names slugifying
                // the same way within one TL (rare, but keeps emails unique).
                $slug = $baseSlug;
                $dupe = 1;
                while (in_array($slug, $usedSlugs, true)) {
                    $dupe++;
                    $slug = $baseSlug . $dupe;
                }
                $usedSlugs[] = $slug;

                $email = "{$slug}.{$codeSlug}.{$seq}@generallink.my";
                $phone = sprintf('01%d-%03d%04d', mt_rand(0, 9), mt_rand(0, 999), mt_rand(0, 9999));

                if (Agent::where('email', $email)->exists()) {
                    $skipped++;
                    continue;
                }

                $this->line("    {$fullName} <{$email}> — {$phone}");

                if ($dryRun) {
                    $created++;
                    continue;
                }

                $controller->createAgentForImport([
                    'full_name' => $fullName,
                    'email'     => $email,
                    'phone'     => $phone,
                    'address'   => $profile->address,
                    'postcode'  => $profile->postcode,
                    'city'      => $profile->city,
                    'state'     => $profile->state,
                ], 'INTRODUCER', $tl->agent_id, $tl->group_id, $tl->group_label_id);

                $created++;
            }

            $totalCreated += $created;
            $totalSkipped += $skipped;
        }

        $this->info(($dryRun ? '[DRY RUN] Would create' : 'Created') . " {$totalCreated} Introducer(s) total, skipped {$totalSkipped} (already existed).");
        return self::SUCCESS;
    }
}
