<?php

namespace App\Services;

// NEW 9 Aug 2026 — per Chris's detailed spec: Industry and Nature of
// Business must be separate, multi-select, structured classifications
// (not one text field each) — "for AI vendor classification, search,
// matching, due diligence, risk assessment, reporting." Deliberately a
// DIFFERENT, longer list than App\Http\Controllers\Admin\VendorController
// ::INDUSTRIES (which stays as-is for Admin's own internal quick-add
// vendor form) — this is the list Chris gave specifically for the
// vendor's own multi-select registration screen.
class VendorClassificationService
{
    public const INDUSTRIES = [
        'AGRICULTURE_FARMING'                  => 'Agriculture & Farming',
        'AUTOMOTIVE'                            => 'Automotive',
        'BANKING_FINANCIAL_SERVICES'            => 'Banking & Financial Services',
        'CONSTRUCTION_BUILDING'                 => 'Construction & Building',
        'EDUCATION_TRAINING'                    => 'Education & Training',
        'ENGINEERING'                            => 'Engineering',
        'ENERGY_UTILITIES'                       => 'Energy & Utilities',
        'FOOD_BEVERAGE'                           => 'Food & Beverage',
        'GOVERNMENT_PUBLIC_SECTOR'               => 'Government & Public Sector',
        'HEALTHCARE_MEDICAL'                     => 'Healthcare & Medical',
        'HOSPITALITY_TOURISM'                    => 'Hospitality & Tourism',
        'INFORMATION_TECHNOLOGY'                 => 'Information Technology',
        'INSURANCE'                               => 'Insurance',
        'LOGISTICS_TRANSPORTATION'               => 'Logistics & Transportation',
        'MANUFACTURING'                           => 'Manufacturing',
        'PROFESSIONAL_SERVICES'                  => 'Professional Services',
        'PROPERTY_REAL_ESTATE'                   => 'Property & Real Estate',
        'RETAIL'                                  => 'Retail',
        'WHOLESALE_DISTRIBUTION'                 => 'Wholesale & Distribution',
        'TELECOMMUNICATIONS'                      => 'Telecommunications',
        'TRADING'                                  => 'Trading',
        'E_COMMERCE'                               => 'E-Commerce',
        'OIL_GAS'                                  => 'Oil & Gas',
        'PHARMACEUTICAL'                          => 'Pharmaceutical',
        'MEDIA_ENTERTAINMENT'                    => 'Media & Entertainment',
        'AGRICULTURE_PLANTATION'                 => 'Agriculture & Plantation',
        'ENVIRONMENTAL_SERVICES'                 => 'Environmental Services',
        'SECURITY_SERVICES'                      => 'Security Services',
        'TELECOMMUNICATIONS_NETWORK_SERVICES'    => 'Telecommunications & Network Services',
        'OTHER'                                    => 'Other',
    ];

    public const BUSINESS_ACTIVITIES = [
        'MANUFACTURING'                  => 'Manufacturing',
        'WHOLESALE_DISTRIBUTION'         => 'Wholesale & Distribution',
        'RETAIL'                          => 'Retail',
        'TRADING_GENERAL'                => 'Trading & General Trading',
        'IMPORT_EXPORT'                   => 'Import & Export',
        'ECOMMERCE_ONLINE'               => 'E-Commerce & Online Business',
        'IT_SOFTWARE'                     => 'Information Technology & Software',
        'IT_SYSTEM_INTEGRATION'          => 'IT System Integration',
        'HARDWARE_EQUIPMENT_SUPPLY'      => 'Hardware & Equipment Supply',
        'TELECOMMUNICATIONS'             => 'Telecommunications',
        'NETWORK_INFRASTRUCTURE'         => 'Network Infrastructure',
        'CYBERSECURITY'                   => 'Cybersecurity',
        'CLOUD_DATA_SERVICES'            => 'Cloud & Data Services',
        'AI_TECHNOLOGY_SOLUTIONS'        => 'Artificial Intelligence & Technology Solutions',
        'PROFESSIONAL_CONSULTING'        => 'Professional Consulting',
        'MANAGEMENT_CONSULTING'          => 'Management Consulting',
        'BUSINESS_CONSULTING'            => 'Business Consulting',
        'ENGINEERING_SERVICES'           => 'Engineering Services',
        'CONSTRUCTION_BUILDING'          => 'Construction & Building',
        'PROPERTY_DEVELOPMENT'           => 'Property Development',
        'PROPERTY_MANAGEMENT'            => 'Property Management',
        'FACILITIES_MANAGEMENT'          => 'Facilities Management',
        'MAINTENANCE_REPAIR'             => 'Maintenance & Repair Services',
        'ELECTRICAL_ELECTRONIC'          => 'Electrical & Electronic Services',
        'MECHANICAL_SERVICES'            => 'Mechanical Services',
        'ARCHITECTURE_DESIGN'            => 'Architecture & Design',
        'ACCOUNTING_AUDIT'               => 'Accounting & Audit',
        'LEGAL_SERVICES'                  => 'Legal Services',
        'FINANCIAL_SERVICES'             => 'Financial Services',
        'INSURANCE_RISK_MANAGEMENT'      => 'Insurance & Risk Management',
        'HR_RECRUITMENT'                  => 'Human Resources & Recruitment',
        'TRAINING_EDUCATION'             => 'Training & Education',
        'HEALTHCARE_MEDICAL'             => 'Healthcare & Medical Services',
        'PHARMACEUTICALS_MEDICAL_SUPPLIES' => 'Pharmaceuticals & Medical Supplies',
        'FOOD_BEVERAGE'                    => 'Food & Beverage',
        'HOSPITALITY_HOTELS'             => 'Hospitality & Hotels',
        'TOURISM_TRAVEL'                  => 'Tourism & Travel Services',
        'TRANSPORTATION_LOGISTICS'       => 'Transportation & Logistics',
        'WAREHOUSING_STORAGE'            => 'Warehousing & Storage',
        'AUTOMOTIVE_VEHICLE_SERVICES'    => 'Automotive & Vehicle Services',
        'AGRICULTURE_FARMING'            => 'Agriculture & Farming',
        'FISHERIES_AQUACULTURE'          => 'Fisheries & Aquaculture',
        'ENERGY_UTILITIES'                => 'Energy & Utilities',
        'OIL_GAS'                          => 'Oil & Gas',
        'ENVIRONMENTAL_SERVICES'         => 'Environmental Services',
        'CLEANING_SANITATION'            => 'Cleaning & Sanitation Services',
        'SECURITY_SERVICES'              => 'Security Services',
        'MARKETING_ADVERTISING'          => 'Marketing & Advertising',
        'MEDIA_ENTERTAINMENT'            => 'Media & Entertainment',
        'PRINTING_PUBLISHING'            => 'Printing & Publishing',
        'EVENT_MANAGEMENT'                => 'Event Management',
        'INTERIOR_DESIGN_FURNISHING'     => 'Interior Design & Furnishing',
        'TEXTILE_GARMENT'                 => 'Textile & Garment',
        'BEAUTY_PERSONAL_CARE'           => 'Beauty & Personal Care',
        'WHOLESALE_FOOD_SUPPLY'          => 'Wholesale Food Supply',
        'OFFICE_SUPPLIES_STATIONERY'     => 'Office Supplies & Stationery',
        'SECURITY_SYSTEMS_ACCESS'        => 'Security Systems & Access Control',
        'FIRE_PROTECTION_SAFETY'         => 'Fire Protection & Safety Equipment',
        'CLEANING_EQUIPMENT_SUPPLIES'    => 'Cleaning Equipment & Supplies',
        'GENERAL_SERVICES'                => 'General Services',
        'OTHER'                            => 'Other Business Activities',
    ];
}
