<?php
return [
    ['code' => '01', 'name_en' => 'Cash & Bank', 'name_zh' => '现金与银行'],
    ['code' => '02', 'name_en' => 'Receivables', 'name_zh' => '应收款项'],
    ['code' => '03', 'name_en' => 'Inventory', 'name_zh' => '存货'],
    ['code' => '04', 'name_en' => 'Prepayments', 'name_zh' => '预付款项'],
    ['code' => '05', 'name_en' => 'Fixed Assets', 'name_zh' => '固定资产'],
    ['code' => '06', 'name_en' => 'Accumulated Depreciation', 'name_zh' => '累计折旧'],
    ['code' => '07', 'name_en' => 'Payables', 'name_zh' => '应付款项'],
    ['code' => '08', 'name_en' => 'Accrued & Deferred Items', 'name_zh' => '应计与递延项目'],
    ['code' => '09', 'name_en' => 'Statutory & Tax Liabilities', 'name_zh' => '法定与税务负债'],
    ['code' => '10', 'name_en' => 'Funds / Equity', 'name_zh' => '基金/权益'],
    ['code' => '11', 'name_en' => 'Donation & Offering Income', 'name_zh' => '捐款与献仪收入'],
    ['code' => '12', 'name_en' => 'Religious Service & Ceremonial Income', 'name_zh' => '宗教仪式服务收入'],
    ['code' => '13', 'name_en' => 'Event & Membership Income', 'name_zh' => '活动与会员收入'],
    ['code' => '14', 'name_en' => 'Sales & Rental Income', 'name_zh' => '销售与租金收入'],
    ['code' => '15', 'name_en' => 'Investment & Other Income', 'name_zh' => '投资及其他收入'],
    ['code' => '16', 'name_en' => 'Religious & Ceremony Expense', 'name_zh' => '宗教与仪式支出'],
    ['code' => '17', 'name_en' => 'Entity Maintenance & Utilities Expense', 'name_zh' => '场地维修与水电支出'],
    ['code' => '18', 'name_en' => 'Staff Cost', 'name_zh' => '员工成本'],
    ['code' => '19', 'name_en' => 'Administrative Expense', 'name_zh' => '行政支出'],
    ['code' => '20', 'name_en' => 'Banking & Finance Expense', 'name_zh' => '银行与融资费用'],
    ['code' => '21', 'name_en' => 'Charity & Welfare Expense', 'name_zh' => '慈善与福利支出'],
    ['code' => '22', 'name_en' => 'Depreciation & Insurance Expense', 'name_zh' => '折旧与保险费用'],
    ['code' => '23', 'name_en' => 'Security & Vehicle Expense', 'name_zh' => '保安与车辆费用'],
    ['code' => '24', 'name_en' => 'Fundraising & Promotion Expense', 'name_zh' => '筹款与宣传费用'],
    ['code' => '25', 'name_en' => 'Entertainment Expense', 'name_zh' => '交际及款待费用'],
    ['code' => '26', 'name_en' => 'Other Expense', 'name_zh' => '其他支出'],
];
